### ISSUE TITLE
如何在Mac下连接ssh网络硬盘？

### ISSUE THREAD

**Issue by HuangJiaLian** [HuangJiaLian/SystemTechDiscuss#4]
为了能够在方便地在Linux和Mac传输文件, 如何在Mac下连接ssh网络硬盘？

**Comment by HuangJiaLian** [comment]
1. 安装 [Homebrew](https://brew.sh/)
```bash
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
```

2. 安装osxfuse
```bash
brew cask install osxfuse
```

3. 安装
```bash
brew install sshfs
```

4. 挂载网络硬盘
```bash
sshfs username@server_address:/remote/path/wanted   /Local/folder/to/mount/ONTO  -ovolname=NAME
```
例如, 下面的命令将我的Linux电脑的主目录挂载到我的Mac下的Jack_soft文件夹。
```bash
sshfs jack@192.168.101.82:/home/jack/ /Users/mac/Mounts/Jack_soft -ovolname=Jack_soft
```
不过这么长的命令可以不用去记忆，我们可以在`.bash_profile`里面添加一别名，这样每次要连接网络硬盘的时候只需要输入别名就可以了。
例如我的别名设置是:

```bash
alias Jmount_soft='sshfs jack@192.168.101.82:/home/jack/ /Users/mac/Mounts/Jack_soft -ovolname=Jack_soft'
```

这样每次只要在命令行里面输入`Jmount_soft`就可以在Finder中出现我的Linux文件了。

**Comment by 974918051** [comment]
第四步的时候：
`'sshfs ya@10.1.17.50:/public/home/ya/ /Users/yaa/Ya_simulation -ovolname=Ya_simulation'`
注意一下集群上面自己账号对应的路径，命令`cd;pwd`查看。
